#name of the pipline
name: github action demo pipeline

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    run on: ubuntu-latest

    steps:
      - name: checkput code
        uses: actions/checkout@v2

      - name: print message
        run: echo "welcome mayur"
